### ISSUE TITLE
Error when bundling tweetsodium with webpack

### ISSUE THREAD

**Issue by joshcai** [mastahyeti/tweetsodium#13]
When using version 0.0.5 of tweetsodium with webpack, I end up getting this error when running a webpack-bundled file:

"Uncaught TypeError: Cannot set property 'overheadLength' of undefined"

The webpack build process itself works fine, the error only appears when running the code. This isn't blocking me since using version 0.0.4 works perfectly fine - webpack is able to bundle that version with no issues at all, so I suspect it is related to the change that added TypeScript type definitions. 

In case it helps, here was the webpack config I was using when I found this issue: https://github.com/joshcai/leetcode-sync-chrome/commit/e2226d73eb44acb358cc390efbb6e8f8ed12d00f#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f

Thanks for providing this library - I had no other issues once switching to the 0.0.4 version.

**Comment by lgarron** [comment]
Closing this because we have deprecated `tweetsodium`.
