### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by jclem** [mastahyeti/tweetsodium#2]
We are currently vendoring in e6c0cb441e2717d217a55380b1f8b514c43c7c77, which I don't think is the version published on NPM, but it's difficult to tell.

Would you mind tagging releases in the future, and also releasing a new version at e6c0cb441e2717d217a55380b1f8b514c43c7c77 if that's not what's already in v0.0.1?

**Comment by btoews** [comment]
I published a new 0.0.2 release on NPM and added a tag for it in the repo.

**Comment by jclem** [comment]
Thanks!
